### ISSUE TITLE
Python 3 compatibility of notebook_sphinxext.py

### ISSUE THREAD

**Issue by mgeier** [matthew-brett/perrin-academy#2]
I found your repository while searching for `notebook_sphinxext.py`.
You seem to have made a few modifications to the original at https://github.com/ngoldbaum/RunNotebook, and I wanted to give it a try.

It works nicely with Python 2.7, but there are some issues with Python 3:

This [line](https://github.com/matthew-brett/perrin-academy/blob/master/sphinxext/notebook_sphinxext.py#L135)

``` python
f.write(script_text.encode('utf8'))
```

... doesn't work because `write()` seems to expect a `str`, but `encode()` returns a `bytes` in Python 3.

I don't know what's the right solution, I just removed the `encode()` call, which works for me, but for sure there is a more general solution, which works on both Python 2 and 3.

There are also 2 warnings, caused by those two lines:

``` python
from IPython.nbconvert import html, python
from IPython import nbformat
```

Which, I guess, should be changed to something like:

``` python
from nbconvert import html, python
import nbformat
```

But probably both ways should be tried.

**Comment by matthew-brett** [comment]
Thanks a lot for taking the time to write an issue.  I think taking out the encode step should be OK, but I'll have a think about that.

**Comment by matthew-brett** [comment]
I've had a go at updating the code / site for Python 3 - does it work for you?

**Comment by mgeier** [comment]
Sadly, I get a different error after your changes:

```
[...]
  File "[...]/notebook_sphinxext.py", line 130, in run
    nb = nbf.read_json(f)
  File "/usr/local/lib/python3.4/dist-packages/nbformat/v3/nbjson.py", line 29, in reads
    nb = json.loads(s, **kwargs)
  File "/usr/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'TextIOWrapper'
```

BTW, in the meantime I found out that there is no need for `runipy` anymore since `nbconvert` can execute the notebook with its [ExecutePreprocessor](http://nbconvert.readthedocs.org/en/latest/api/preprocessors.html#nbconvert.preprocessors.ExecutePreprocessor). There is [another preprocessor for removing the output](http://nbconvert.readthedocs.org/en/latest/api/preprocessors.html#nbconvert.preprocessors.ClearOutputPreprocessor).

Also, I think that it would be better to create one page per notebook automatically, instead of creating RST files which contain (typically) only one `.. notebook::` directive.

I started to try to go another path with https://github.com/mgeier/nbsphinx, but I'm not sure how far this will carry me ...

**Comment by matthew-brett** [comment]
Thanks - fixed I think.

I've personally started to move away from notebooks for static sites, and I now convert notebooks to sphinx pages, using the sphinx page as primary source : https://pypi.python.org/pypi/nb2plots

**Comment by mgeier** [comment]
Now I'm getting yet another error:

```
[...]
  File "[...]/notebook_sphinxext.py", line 135, in run
    nbformat.write(nb, f, as_version=NBFORMAT)
  File "/usr/local/lib/python3.4/dist-packages/IPython/nbformat/__init__.py", line 158, in write
    s = writes(nb, version, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/IPython/nbformat/__init__.py", line 104, in writes
    return versions[version].writes_json(nb, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/IPython/nbformat/v3/nbjson.py", line 49, in writes
    return py3compat.str_to_unicode(json.dumps(nb, **kwargs), 'utf-8')
  File "/usr/lib/python3.4/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
TypeError: __init__() got an unexpected keyword argument 'as_version'
```

The `write()` function seems to have a `version` argument, but not `as_version`.
https://nbformat.readthedocs.org/en/latest/api.html#nbformat.write

Your `nb2plots` package looks interesting. Do you happen to have an example project where this is in use?
Are you using custom styling for the HTML/LaTeX output?
I would be really interested in how to make an rST source that (after running Sphinx) looks similar to the HTML/LaTeX output of `nbconvert` ...
I have no clue about Jinja templates and docutils, so I don't know if such a thing is realistic or not.

**Comment by matthew-brett** [comment]
Ouch - just goes to show that having a project without proper tests doesn't scale very well.

One problem with writing the output is that sphinx has it's own css, that comes from the sphinx theme.  I actually don't like the page to look notebook-like, I want the page to look and behave as if it is part of the sphinx project, hence my shift. 

I'm using `nb2plots` in - say - this project:

http://www.jarrodmillman.com/rcsds/lectures/index.html

These being examples of stuff converted from notebooks, then edited:

http://www.jarrodmillman.com/rcsds/lectures/boolean_indexing.html
http://www.jarrodmillman.com/rcsds/lectures/modeling_noise.html

I like the way these pages look, and the fact I can doctest them to check the results are the same.  I do want to make the pages available as ipython notebooks though, and I hope that I can finish that up in the next couple of weeks.  The idea would be that this part of the project embeds a link in the build sphinx page, on the lines of `download as notebook`, where the sphinx build would generate the notebook and execute it, then put it into the build html directory.

**Comment by mgeier** [comment]
Yes, now it works for me, thanks for the fixes!

Thanks for the links, those pages look very interesting.

I appreciate the doctest angle, but for my use case I'd rather not have the `>>>` prompt all over the place. Also, I would like to include notebooks with mainly plots in them, which cannot really be checked by doctests anyway.

If you are interested, this is the project where I want to include notebooks into Sphinx docs: http://sfs.readthedocs.org/en/latest/.

For the API docs, I'm already using the `matplotlib.sphinxext.plot_directive`, but it is quite cumbersome to edit the code, because building the docs takes some time and in case of errors it's a pain to find out what went wrong.
Therefore I would like to use notebooks in other parts of the docs.
The notebooks can be quickly edited and the plots are visible immediately.
I don't want to convert them to RST up front, because I would like to be able to make future changes within Jupyter.
I would like to use the notebooks directly as source files (which already partly works) and let Sphinx generate HTML and PDF versions of the docs.
The HTML version should include a "download as notebook" links, as you are suggesting.

Currently, I'm stuck at finding the right directory where to put the image files for the figures.

And I've not even started to tackle the harder problem of styling the code cells.

**Comment by matthew-brett** [comment]
Thanks for your thoughts, they help me think about the problem.

I know what you mean about the `>>>` prompts.   They can be turned on or off with a javascript extension  - as for this page: 

http://www.jarrodmillman.com/rcsds/lectures/slicing_with_booleans.html

They could of course be off by default, but that's not always ideal.

I agree the `plot_directive` can get pretty slow.   I've got a copy of the plot directive in my project, and I've done some work on it already.   I think repeated builds could be sped up, which is my main annoyance, but a from-scratch build will likely continue to be slow.

You're quite right about the debugging, I will do some work on that.  I was thinking having another builder, such as `plot-debug` in which you would be dropped into an IPython prompt at an error.

My own problem is that I greatly dislike fine-tuning and reorganizing stuff in notebooks, because I find the web interface tiring for anything other than a single session of linear exploration.   I also miss the ability to drop in my own extensions, add nice footnotes and references, the ability to share links across pages, and all those other nice sphinx things.  Also there's the problem of diff'ing the notebooks, for collaboration.

**Comment by mgeier** [comment]
Sorry that I'm abusing these comments to an already resolved issue for general discussion, but I find this quite interesting ...

I like your idea about a custom debugging-enabled builder, this could be really helpful.
But I also like the idea that the content can be debugged quickly as Jupyter notebook and once everything works, it's merely converted to Sphinx (hopefully without errors).

If you dislike working in a Jupyter notebook, that's of course not a solution for you.
But I actually like it and I know of some colleagues and students who prefer working in the browser notebook instead of plain `.py` files or on a terminal Python prompt.

But of course that's a matter of taste.

> I also miss the ability to drop in my own extensions, add nice footnotes and references, the ability to share links across pages, and all those other nice sphinx things.

OK, I see that this is an inconvenience, but wouldn't you automatically loose the ability to convert your pages back to notebooks?

I'm also not sure why you want to export notebook even though you dislike working in them.

And I think some of the limitations you mentioned can probably be overcome.
I will try if it's possible to re-write relative links to notebooks into Sphinx-compatible links during conversion. I think this might work.

I did some more work on [my extension](https://github.com/mgeier/nbsphinx), but there are still many things left to do.

I also have some open problems, probably you can help me with those?
- https://groups.google.com/forum/?nomobile=true#!topic/sphinx-dev/0chv7BsYuW0
- https://github.com/sphinx-doc/sphinx/issues/2162

>  Also there's the problem of diff'ing the notebooks, for collaboration.

Of course, that's a problem.

But I think the Jupyter people are actively working on the collaboration aspect, I'm sure there will be significant progress in the next few years.

I also think that saving empty (un-executed) notebooks in the repo helps, but of course many conflicts might be very hard to resolve.

**Comment by matthew-brett** [comment]
I find that what I am doing now, is sketching up something in the notebook, but without adding many comments or notes.   When I have a set of cells that does something useful, I convert it to the `.rst` file and do the rest of my edits there.

Yes, of course sphinx / ReST is a more capable format that the notebook, so you'd lose some stuff converting to a notebook, but the notebook would only be for playing with the content, not the source of the content, so if we lost footnotes or cross-links, that wouldn't matter very much.

I also know a lot of people who prefer working in the notebook, and I think I've put a few of my students in that position, but I think it's not a good model for daily work.  For me, I find the browser and GUI distracting, and it makes it considerably harder for me to think about the problem.   In fact, part of my motivation for this project was to try to avoid encouraging the students to use the notebook as their main working model.

You may have come across these:
- http://opiateforthemass.es/articles/why-i-dont-like-jupyter-fka-ipython-notebook/
- https://khinsen.wordpress.com/2015/09/03/beyond-jupyter-whats-in-a-notebook/

The problems they are talking about are ones I've been worrying about for a few years now.

**Comment by mgeier** [comment]
Thanks for the links, I haven't read those before, very interesting.

They make some very good points, but they don't really provide an alternative, do they?
I don't think ActivePapers is a reasonable alternative, since it causes even more "lock in", it isn't easily accessible via a web browser (compared to nbviewer) and AFAICT nobody uses it anyway.

I think some of the problems they describe come from using the notebook for the wrong things.
I wouldn't use the notebook for every line of Python code I'm writing.
I prefer to use the notebook for things with little Python code and many images and (Markdown) descriptions. As soon as I have larger amounts of Python code, I prefer to move it into separate `.py` files and `import` them in my notebook.
I also don't like to have long-running pieces of code in my notebook. In this case I prefer to have a "normal" Python script to crunch the data and save the results, which I can then analyze in the notebook (and this can be re-executed fairly quickly).

Some other problems can hopefully be solved, and I' trying to solve them one at a time, and now I've managed to re-write links to local notebook files during Sphinx processing, see http://nbsphinx.readthedocs.org/en/latest/example.html#links-to-other-notebooks and https://github.com/mgeier/nbsphinx/commit/78163b15cbdbf080212f927cd9238b417163cbd1.
These links work correctly in Jupyter, in nbviewer and in the Sphinx-generated HTML and LaTeX docs.
I think that's quite useful, isn't it?

Of course, there is still a lot of work to do and many other problems to solve ...

**Comment by matthew-brett** [comment]
At the moment my main interest is teaching.

Unfortunately, it notebook is so pleasant for preparing teaching stuff that it's very tempting to use it as the default Python console in the class.  I've done that heavily in a couple of classes I was teaching.

The problem is that the student then starts to use that as their default Python environment, and I believe (without much data yet) that that will make it harder for them to learn good coding practice.

It sounds like your and my coding practice is about the same.  I really only use the IPython notebook when I'm experimenting with something that has a lot of plots, or drafting up a tutorial.   I think that's more or less the same for most of the experienced scientific Python people I know.

**Comment by mgeier** [comment]
I think it's time to close this issue ...

I've been working a bit more on [nbsphinx](http://nbsphinx.readthedocs.org/) and I think it's already quite useful.

My supervisor has created quite a few notebooks for teaching signal processing: https://github.com/spatialaudio/digital-signal-processing-lecture
We'll probably use `nbsphinx` to provide HTML and PDF versions of this on readthedocs.org, [first experiments](http://dsp-nbsphinx.readthedocs.org/) (temporary link) look promising ...
